import React from 'react';
import { Zap, Layers, Sparkles, Trophy, Grid, Crown, Flame, Percent, PackagePlus, Ticket } from 'lucide-react';
import type { HomepageSectionConfig } from '@/config/homepageConfig';

export interface PresetComponent {
  id: string;
  name: string;
  desc: string;
  group: 'PRODUCT' | 'BANNER';
  isAuto?: boolean;
  createConfig: () => Omit<HomepageSectionConfig, 'id'>;
  renderIcon: () => React.ReactNode;
}

export const PRESET_COMPONENTS: PresetComponent[] = [
  // --- Flash Sale & Khuyến mãi ---
  {
    id: 'comp_flash_sale',
    name: 'Flash Sale Giờ Vàng',
    desc: 'Ưu đãi chớp nhoáng có đồng hồ đếm ngược',
    group: 'PRODUCT',
    isAuto: true,
    renderIcon: () => <Zap size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'FLASH_SALE',
      title: 'Flash Sale Giờ Vàng',
      subtitle: 'Ưu đãi chớp nhoáng – Số lượng giới hạn theo khung giờ',
      enabled: true,
      dataSource: 'FLASH_SALE',
      displayStyle: 'SLIDER',
      itemLimit: 10,
      showViewAll: true,
      viewAllUrl: '/books',
    }),
  },
  {
    id: 'comp_category_circles',
    name: 'Danh Mục Sách Dạng Tròn',
    desc: 'Bong bóng thể loại phong cách Story',
    group: 'BANNER',
    renderIcon: () => <Layers size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'CATEGORY_CIRCLES',
      title: 'Khám Phá Thể Loại Sách',
      subtitle: 'Danh mục tuyển chọn theo chủ đề & phong cách',
      enabled: true,
      dataSource: 'CATEGORY',
      displayStyle: 'GRID',
      itemLimit: 10,
      showViewAll: false,
    }),
  },
  {
    id: 'comp_recommendations',
    name: 'Gợi Ý Cá Nhân Hóa (AI)',
    desc: 'Thuật toán gợi ý theo thói quen đọc',
    group: 'PRODUCT',
    isAuto: true,
    renderIcon: () => <Sparkles size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'RECOMMENDATIONS',
      title: 'Gợi Ý Dành Riêng Cho Bạn',
      subtitle: 'Dựa trên sở thích đọc và tương tác gần đây',
      enabled: true,
      dataSource: 'PERSONALIZED',
      displayStyle: 'GRID',
      itemLimit: 8,
      showViewAll: false,
    }),
  },
  {
    id: 'comp_top_best_sellers',
    name: 'Top Bán Chạy',
    desc: 'Xếp hạng top 10 trượt ngang',
    group: 'PRODUCT',
    isAuto: true,
    renderIcon: () => <Trophy size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'BEST_SELLERS',
      title: 'Top Sản Phẩm Bán Chạy',
      subtitle: 'Xếp hạng 10 tựa sách & truyện tranh bán chạy nhất tuần qua',
      enabled: true,
      dataSource: 'BEST_SELLING',
      displayStyle: 'RANKING',
      sortBy: 'VIEWS_DESC',
      itemLimit: 10,
      showViewAll: true,
      viewAllUrl: '/books',
    }),
  },
  {
    id: 'comp_category_grid',
    name: 'Sản Phẩm Theo Ngành',
    desc: 'Lưới sách phân loại (Truyện tranh, Manga...)',
    group: 'PRODUCT',
    renderIcon: () => <Grid size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'CATEGORY_LIST',
      title: 'Truyện Tranh & Manga Nổi Bật',
      subtitle: 'Tuyển tập các bộ truyện tranh đình đám với quà tặng và bookmark độc quyền',
      enabled: true,
      dataSource: 'CATEGORY',
      displayStyle: 'GRID',
      sortBy: 'NEWEST',
      categoryId: 2,
      categoryName: 'Sách Thiếu nhi',
      itemLimit: 8,
      showViewAll: true,
      viewAllUrl: '/books?category=2',
    }),
  },
  {
    id: 'comp_vip_members_slider',
    name: 'Sách Hội Viên VIP',
    desc: 'Trượt ngang ưu đãi 49K & Đọc thử VIP',
    group: 'PRODUCT',
    renderIcon: () => <Crown size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'DAILY_VIP',
      title: 'Sách Mới Mỗi Ngày – Dành Cho Hội Viên',
      subtitle: 'Độc quyền trải nghiệm đọc thử trọn vẹn dành riêng cho thành viên VIP',
      enabled: true,
      dataSource: 'VIP_MEMBERS',
      displayStyle: 'SLIDER',
      itemLimit: 8,
      showViewAll: true,
      viewAllUrl: '/books',
    }),
  },
  {
    id: 'comp_hot_tabs',
    name: 'Sản Phẩm Nổi Bật (Tabs)',
    desc: 'Chia theo tab Bản đặc biệt, Manga, LN',
    group: 'PRODUCT',
    renderIcon: () => <Flame size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'HOT_RECOMMENDED',
      title: 'Gợi Ý Sách & Truyện Hot',
      subtitle: 'Khám phá các phiên bản đặc biệt, boxset giới hạn & bản thường mới nhất',
      enabled: true,
      dataSource: 'FEATURED_TABS',
      displayStyle: 'GRID',
      itemLimit: 8,
      showViewAll: false,
    }),
  },
  {
    id: 'comp_discounted_deals',
    name: 'Sách Giảm Giá Sốc',
    desc: 'Tự động lọc sách giảm giá sâu nhất',
    group: 'PRODUCT',
    isAuto: true,
    renderIcon: () => <Percent size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'CATEGORY_LIST',
      title: 'Siêu Giảm Giá Sách Tháng Này',
      subtitle: 'Ưu đãi giảm giá sâu lên tới 50% dành cho bạn',
      enabled: true,
      dataSource: 'DISCOUNTED',
      displayStyle: 'GRID',
      sortBy: 'DISCOUNT_DESC',
      itemLimit: 8,
      showViewAll: true,
      viewAllUrl: '/books',
    }),
  },
  {
    id: 'comp_latest_arrivals',
    name: 'Sách Mới Nhập Kho',
    desc: 'Tự động hiển thị sách mới lên kệ',
    group: 'PRODUCT',
    isAuto: true,
    renderIcon: () => <PackagePlus size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'CATEGORY_LIST',
      title: 'Sách Mới Vừa Cập Bến',
      subtitle: 'Cập nhật những tựa sách mới nhất trong kho hàng',
      enabled: true,
      dataSource: 'LATEST',
      displayStyle: 'GRID',
      sortBy: 'NEWEST',
      itemLimit: 8,
      showViewAll: true,
      viewAllUrl: '/books',
    }),
  },
  {
    id: 'comp_vouchers',
    name: 'Vé Ưu Đãi Voucher',
    desc: 'Khối mã giảm giá vận chuyển & đơn hàng',
    group: 'BANNER',
    renderIcon: () => <Ticket size={20} strokeWidth={2.2} />,
    createConfig: () => ({
      type: 'VOUCHERS',
      title: 'Mã Giảm Giá & Ưu Đãi Vận Chuyển',
      subtitle: 'Thu thập voucher freeship và giảm giá ngay hôm nay',
      enabled: true,
      dataSource: 'VOUCHERS',
      displayStyle: 'GRID',
      itemLimit: 4,
      showViewAll: false,
    }),
  },
];
