import type { CarrierConfig, StoreGeneralConfig } from '@/types';

export const defaultCarrierConfigs: CarrierConfig[] = [
  {
    code: 'SPX',
    name: 'SPX Express (Shopee Xpress)',
    logo: '/carriers/spx.webp',
    isActive: true,
    baseFee: 22000,
    weightStepFee: 5000,
    deliveryDays: '1 - 2 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://open-api.spx.vn/api/v1/orders/create',
    productionEndpoint: 'https://open-api.spx.vn/api/v1/orders/create',
    notes: 'Mạng lưới chuyển phát nhanh SPX giao nhanh toàn quốc',
  },
  {
    code: 'JT_EXPRESS',
    name: 'J&T Express',
    logo: '/carriers/j&t.jpg',
    isActive: true,
    baseFee: 20000,
    weightStepFee: 5000,
    deliveryDays: '2 - 3 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://jtservices.vn/api/order/create',
    productionEndpoint: 'https://jtservices.vn/api/order/create',
    notes: 'Phủ sóng 63 tỉnh thành, giao hàng kể cả thứ 7 & Chủ nhật',
  },
  {
    code: 'GHN',
    name: 'Giao Hàng Nhanh (GHN)',
    logo: '/carriers/ghn.jpg',
    isActive: true,
    baseFee: 24000,
    weightStepFee: 5000,
    deliveryDays: '1 - 2 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create',
    productionEndpoint: 'https://online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/create',
    notes: 'Chuyên tuyến giao nhanh, hỗ trợ thu hộ COD chuyên nghiệp',
  },
  {
    code: 'GHTK',
    name: 'Giao Hàng Tiết Kiệm (GHTK)',
    logo: '/carriers/ghtk.jpg',
    isActive: true,
    baseFee: 20000,
    weightStepFee: 5000,
    deliveryDays: '2 - 3 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://services.giaohangtietkiem.vn/services/shipment/order',
    productionEndpoint: 'https://services.giaohangtietkiem.vn/services/shipment/order',
    notes: 'Cước phí tiết kiệm, app quản lý đơn bưu tá tiện lợi',
  },
  {
    code: 'VIETTEL_POST',
    name: 'Viettel Post',
    logo: '/carriers/viettel.png',
    isActive: true,
    baseFee: 22000,
    weightStepFee: 5000,
    deliveryDays: '2 - 3 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://partner.viettelpost.vn/v2/order/createOrder',
    productionEndpoint: 'https://partner.viettelpost.vn/v2/order/createOrder',
    notes: 'Mạng lưới bưu chính quân đội bảo đảm an toàn bưu phẩm',
  },
  {
    code: 'VNPOST',
    name: 'VNPost (Bưu Điện Việt Nam)',
    logo: '/carriers/vnpost.png',
    isActive: true,
    baseFee: 18000,
    weightStepFee: 4000,
    deliveryDays: '3 - 4 ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    sandboxEndpoint: 'https://api.vnpost.vn/customer/orders',
    productionEndpoint: 'https://api.vnpost.vn/customer/orders',
    notes: 'Mạng lưới bưu cục rộng khắp xã phường, vùng sâu vùng xa',
  },
  {
    code: 'OTHER',
    name: 'Đơn Vị Khác / Tự Giao',
    logo: '',
    isActive: true,
    baseFee: 20000,
    weightStepFee: 5000,
    deliveryDays: 'Trong ngày',
    apiToken: '',
    shopId: '',
    isSandbox: true,
    notes: 'Cửa hàng tự giao hàng hoặc đối tác giao hỏa tốc địa phương',
  },
];

export const defaultStoreGeneralConfig: StoreGeneralConfig = {
  storeName: 'Boki Bookstore',
  hotline: '1900 8888',
  email: 'contact@boki.vn',
  senderAddress: 'Tòa nhà Boki, 123 Đường Sách, Q. 1, TP. Hồ Chí Minh',
  senderPhone: '0901234567',
  defaultShippingNote: 'Cho xem hàng, không cho thử. Hàng sách báo cẩn thận tránh ẩm ướt.',
};
